# Change these first
owner: petermenocal # Your GitHub username
repo: uptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Exhale Brands
    url: https://www.exhalebrands.com
  - name: Test for HEAD
    method: HEAD
    url: https://www.google.com
  - name: Secret Site
    url: $SECRET_SITE

status-website:
  baseUrl: /uptime # where "repo" is your repository name
  name: Uptime

